server:
  port: 8080
  mode: debug

user_grpc:
  host: localhost
  port: 50051

product_grpc:
  host: localhost
  port: 50052

order_grpc:
  host: localhost
  port: 50053

mysql:
  host: localhost
  port: 3308
  user: seckill
  password: seckill123456
  dbname: seckill
  max_open_conns: 100
  max_idle_conns: 20

redis:
  host: localhost
  port: 6380
  password: ""
  db: 0

rabbitmq:
  host: localhost
  port: 5672
  user: admin
  password: admin123456
  vhost: /

elasticsearch:
  addresses:
    - http://localhost:9200
  index: products
