apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: seckill-product:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              name: http
            - containerPort: 50052
              name: grpc
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: seckill-config
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product
spec:
  selector:
    app: product
  ports:
    - name: http
      port: 8082
      targetPort: 8082
    - name: grpc
      port: 50052
      targetPort: 50052
